# Generated by Django 5.1.5 on 2025-03-03 03:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_productview"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="duration_days",
            field=models.IntegerField(
                blank=True,
                choices=[(30, "1 Month"), (90, "3 Months"), (365, "1 Year")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("premium", "Premium"),
                    ("scalable", "Scalable"),
                ],
                default="basic",
                max_length=10,
            ),
        ),
    ]
