# Generated by Django 5.1.5 on 2025-03-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0003_subscription_duration_days_subscription_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="pending_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="pending_plan",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("premium", "Premium-A"),
                    ("scalable", "Premium-B"),
                ],
                default="basic",
                max_length=10,
            ),
        ),
    ]
