# Generated by Django 5.1.5 on 2025-03-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0005_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="duration_days",
            field=models.IntegerField(
                blank=True,
                choices=[(30, "1 Month"), (180, "6 Months"), (365, "1 Year")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("premium", "Premium (Plan A)"),
                    ("scalable", "Premium (Plan B)"),
                ],
                default="basic",
                max_length=10,
            ),
        ),
    ]
