# Generated by Django 5.1.5 on 2025-03-19 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0006_alter_subscription_duration_days_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("max_products_per_day", models.PositiveIntegerField(default=1)),
                ("base_slots", models.PositiveIntegerField(default=0)),
                ("max_product_views_per_day", models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionDuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration_days", models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="subscription",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customer.plantype",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="duration_days",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customer.subscriptionduration",
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "duration_days",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.subscriptionduration",
                    ),
                ),
                (
                    "plan_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.plantype",
                    ),
                ),
            ],
        ),
    ]
