# Generated by Django 5.1.5 on 2025-03-19 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0007_plantype_subscriptionduration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantype",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="pending_duration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_subscriptions",
                to="customer.subscriptionduration",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="pending_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_subscriptions",
                to="customer.plantype",
            ),
        ),
    ]
