# Generated by Django 5.1.5 on 2025-02-28 13:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_product_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="product_images"
            ),
        ),
    ]
