# Generated by Django 5.1.5 on 2025-03-06 16:34

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="specification",
            field=tinymce.models.HTMLField(),
        ),
    ]
